// generated by newgenasym  Fri Jan 22 17:19:51 2016


module \atsam3u1cb-au  (ad12bvref, advref, dfsdm, dfsdp, dhsdm, dhsdp, erase, fwup,
        gnd1, gnd2, gnd3, gndana, gndbu, gndpll, gndutmi, jtagsel,
        nrst, nrstb, \pa0/pgmncmd , \pa1/pgmrdy , \pa10/pgmd2 ,
        \pa11/pgmd3 , \pa12/pgmd4 , \pa13/pgmd5 , \pa14/pgmd6 ,
        \pa15/pgmd7 , \pa16/pgmd8 , \pa17/pgmd9 , \pa18/pgmd10 ,
        \pa19/pgmd11 , \pa2/pgmnoe , \pa20/pgmd12 , \pa21/pgmd13 ,
        \pa22/pgmd14 , \pa23/pgmd15 , pa24, pa25, pa26, pa27, pa28, pa29,
        \pa3/pgmnvalid , pa30, pa31, \pa4/pgmm0 , \pa5/pgmm1 , \pa6/pgmm2 ,
        \pa7/pgmm3 , \pa8/pgmd0 , \pa9/pgmd1 , pb0, pb1, pb10, pb11, pb12,
        pb13, pb14, pb15, pb16, pb17, pb18, pb19, pb2, pb20, pb21, pb22,
        pb23, pb24, pb3, pb4, pb5, pb6, pb7, pb8, pb9, \tck/swclk , tdi,
        \tdo/traceswo , \tms/swdio , tst, vbg, vddana, vddbu, vddcore1,
        vddcore2, vddcore3, vddcore4, vddcore5, vddin, vddio1,
        vddio2, vddio3, vddio4, vddout, vddpll, vddutmi, xin, xin32,
        xout, xout32);
    inout ad12bvref;
    inout advref;
    inout dfsdm;
    inout dfsdp;
    inout dhsdm;
    inout dhsdp;
    inout erase;
    inout fwup;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gndana;
    inout gndbu;
    inout gndpll;
    inout gndutmi;
    inout jtagsel;
    inout nrst;
    inout nrstb;
    inout \pa0/pgmncmd ;
    inout \pa1/pgmrdy ;
    inout \pa10/pgmd2 ;
    inout \pa11/pgmd3 ;
    inout \pa12/pgmd4 ;
    inout \pa13/pgmd5 ;
    inout \pa14/pgmd6 ;
    inout \pa15/pgmd7 ;
    inout \pa16/pgmd8 ;
    inout \pa17/pgmd9 ;
    inout \pa18/pgmd10 ;
    inout \pa19/pgmd11 ;
    inout \pa2/pgmnoe ;
    inout \pa20/pgmd12 ;
    inout \pa21/pgmd13 ;
    inout \pa22/pgmd14 ;
    inout \pa23/pgmd15 ;
    inout pa24;
    inout pa25;
    inout pa26;
    inout pa27;
    inout pa28;
    inout pa29;
    inout \pa3/pgmnvalid ;
    inout pa30;
    inout pa31;
    inout \pa4/pgmm0 ;
    inout \pa5/pgmm1 ;
    inout \pa6/pgmm2 ;
    inout \pa7/pgmm3 ;
    inout \pa8/pgmd0 ;
    inout \pa9/pgmd1 ;
    inout pb0;
    inout pb1;
    inout pb10;
    inout pb11;
    inout pb12;
    inout pb13;
    inout pb14;
    inout pb15;
    inout pb16;
    inout pb17;
    inout pb18;
    inout pb19;
    inout pb2;
    inout pb20;
    inout pb21;
    inout pb22;
    inout pb23;
    inout pb24;
    inout pb3;
    inout pb4;
    inout pb5;
    inout pb6;
    inout pb7;
    inout pb8;
    inout pb9;
    inout \tck/swclk ;
    inout tdi;
    inout \tdo/traceswo ;
    inout \tms/swdio ;
    inout tst;
    inout vbg;
    inout vddana;
    inout vddbu;
    inout vddcore1;
    inout vddcore2;
    inout vddcore3;
    inout vddcore4;
    inout vddcore5;
    inout vddin;
    inout vddio1;
    inout vddio2;
    inout vddio3;
    inout vddio4;
    inout vddout;
    inout vddpll;
    inout vddutmi;
    inout xin;
    inout xin32;
    inout xout;
    inout xout32;


    initial
        begin
        end

endmodule
